version: '3'

services:
  web:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "Shuai-blog"
    tty: true
    restart: always
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    ports:
      - '127.0.0.1:80:80'
